environment:
  matrix:
    - nodejs_version: "7"

platform:
  - x86
  - x64

init:
  - git config --global core.autocrlf false

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install
  - node --version
  - set PYTHON2=C:\Python27\python.exe

test: off

build_script:
  - node build.js

artifacts:
  - path: 'build\*'

deploy: off
